### ISSUE TITLE
Recherche modérateur et animateur pour le projet

### ISSUE THREAD

**Issue by pascalfares** [ISSAE/smb215-16#11]
Qui parmi vous souhaite m’assister pour être modérateur du groupe SMB215-15 et animateur sur ce projet?

**Comment by CnamLiban** [comment]
Avez vous remarqué l'utilisateur smb21515?

@smb21515

**Comment by mmerhej** [comment]
What is smb21515 user for?

**Comment by mmerhej** [comment]
Sorry re read your comment now.  What is needed in a moderator?

**Comment by Guitta** [comment]
Je suis prête à vous assister

**Comment by smb21515** [comment]
Je suis prêt ...

2015-05-16 14:30 GMT+03:00 Guitta <notifications@github.com>:

**Comment by Ibrahim-Keyrouz** [comment]
@pascalfares  Je suis prêt ...

**Comment by pascalfares** [comment]
Les activités de "modérateur / animateur"

Au niveau management:
1. Suivi et affectation des travaux : en vérifiant ou motivant tous les membres

AU niveaux de la production

1. DBA
2. Responsable intégration : commit dans master
3. Responsable déploiement : préparer les .war - scripts - etc..
4. Responsable test : tester et donner des preuves.

Remarques: Le rôle de modérateur animateur, ne supprime pas le nécessité de participer au réel développement.

Tout le monde doit être capable et le faire:

Développer en Java / JSP / JSF / CSS / HTML5 / Android / SQL

**Comment by Guitta** [comment]
1.1 Spécifier les fonctionnalités du produit "Gestion de stock, inventaire et trace du patrimoine

La gestion des stocks : 
L’ensemble des fonctions de gestion des stocks : inventaire, régule, contrôle, blocage, et d’entreposage : gestion des flux entrée, flux de sortie inventaire, processus de livraison…

La gestion des ressources humaines
La prévision des charges, l’affectation des ressources, le suivi de la planification opérationnel :
Indispensable pour une bonne gestion de l’entrepôt, couvrir la définition des charges en réception, préparation, expédition, l’affectation des ressources sur des missions, et enfin le suivi opérationnel du respect des temps de mission par les opérateurs sur terminaux mobiles.
Suivi de l’ensemble des tâches en présentant les missions en cours avec les retards ou avances.

La gestion du transport : 
La gestion des transporteurs en fonction de critères multiples.


La traçabilité : 
La supervision complète des flux et la possibilité de reconstituer des historiques, des situations par date, par acteur, par produit…
possibilité  de retrouver des erreurs de stock, d’accompagner les plans de retrait des biens … en permettant des croisements multidimensionnels : USER, Article, Lot, Site, Date, Type de mouvement, site Fournisseur, site Client…


Le pilotage
des requêtes ainsi que le paramétrage fonctionnel afin de donner accès à des requêtes précises aux différents utilisateurs.
 
Des Add On complémentaires peuvent être proposé :
	Gestion de la facturation de la prestation logistique (génération de rubrique de facturation, génération d’état de facturation personnalisable, édition de grille de prix…),
	Gestion des bons de livraisons
	Workflow (gestion de tâches automatisées, sur déclencheur, sur timer, manuel, suivi de la réalisation des tâches, mise en place d’alerte…),
Des modules optionnels permettent d’étendre les possibilités :
	Des clients légers pour terminaux Mobile.
	L’ensemble des informations doivent directement être adressées au serveur pour diminuer le risque de perte d’informations.
	Un site Web permettant une saisie déportée des commandes et biens ainsi qu’une consultation des stocks. Cette option assure pour tous les prestataires logistiques un service supplémentaire et renforce leur positionnement stratégique.

**Comment by Hayat5** [comment]
je suis prete

**Comment by smb21515** [comment]
Ces informations doivent être mise dans le projet github 
(https://github.com/pascalfares/smb215-15/tree/master/Docs)
