### ISSUE TITLE
La traçabilité logistique exterieur

### ISSUE THREAD

**Issue by Hayat5** [ISSAE/smb215-16#15]
La traçabilité logistique, appelée également tracking, permet de suivre un produit au niveau quantitatif. Le tracking permet :
•	la localisation d'un produit,
•	l'identification de sa destination et de ses origines.
Les objectifs principaux de la traçabilité logistique sont :
•	le contrôle du chargement,
•	le suivi des commandes et des stocks,
•	la réception des marchandises,
•	le suivi des marchandises,
•	le respect d'une réglementation très stricte,
•	la diminution des erreurs humaines.
La traçabilité logistique permet également de :
•	réduire les délais et les coûts,
•	de retirer des produits non conformes du marché : traçabilité descendante,
•	d'améliorer la qualité des services : traçabilité ascendante.
Les techniques couramment utilisées par les entreprises pour assurer le suivi logistique sont :
•	le code à barres ,la radio identification et RFID

La technique utilise dans ce projet est le RFID

Les specifications seront ajoutes.
Je voulais participer avec @Guitta dans ce projet

**Comment by pascalfares** [comment]
On ne sera pas cappable d'utilise RFID

*___*
*Il est toujours préférable de trouver une solution que de produire des
excuses*
*Pascal Fares <http://www.cofares.net>*

Enseignant ISAE - Cnam Liban
Chef du département informatique <http://depinfo.isae.edu.lb> Cnam Liban

**Comment by pascalfares** [comment]
Les documents ne doivent pas être dans les issues mais dans le git 

créer votre prore git et donner moi le lien

**Comment by Hayat5** [comment]
Le lien de mon projet est https://github.com/Hayat5/smb215

**Comment by pascalfares** [comment]
Le depot 
https://github.com/Hayat5/smb215

est vide!

**Comment by Hayat5** [comment]
Je veux savoir si on peut utiliser une librairie java pour générer qr code et apres on peut l'attacher sur chaque produit comme un label?
Car en utilisant cette librairie on peut le lire sur les smartphones facilement et en plus sur les laptop si le web cam est ouvert et d'autre part c'est moins cher de rfid, et en même temps je pense que je peux mettre comme des capteurs de qrcode sur les portes de chaque salle et quand le produit va passer le système doit indiquer si ce produit entre ou sorte de la salle.
Par rapport au tracibilite extrene je crois que la meilleure méthode est de faire tracking sur le camion qui transporte les produits ou de faire Tracking pour le chauffeur en utilisant son compte gmail.
Je veux juste savoir si je pense de la bonne façon.

**Comment by Hayat5** [comment]
S'il vous plaît vérifier ce lien https://github.com/Hayat5/smb215.
C'est notre travaille jusqu'a maintenant (moi et @Guitta).
Nous sommes en train de travailler pour finir le projet avant le 15 novembre.

**Comment by pascalfares** [comment]
!

**Comment by Guitta** [comment]
Bonsoir.
Est-ce qu'il y a des problèmes?

**Comment by Hayat5** [comment]
Bonsoir Dr Fares,
 J'espère que l'explication de @Guitta a ete plus détaillée que la mienne.
Des explications en plus accompagneront les nouvelles modifications qu'on va apporter à notre projet.
