### ISSUE TITLE
More work needed!!

### ISSUE THREAD

**Issue by pascalfares** [ISSAE/smb215-16#18]
Still waiting for something new

**Comment by antoine-ghosn** [comment]
Hello,
Le projet d'identification à Facebook est localisé sous l'url: https://github.com/antoine-ghosn/SMB215/  (SSO project).
J'ai commencé l'implementation du processus dans la classe SocialMediaHelper.java.
(Vous pouvez trouver un document du descriptions des etapes d'identification sous /docs/facebook_identification.docx)
On doit integrer les 3 projets d' identifications (facebook, twitter et Google) sous un seul projet  apres qu'on fini l'etape d'implementation de ces 3 modules..

**Comment by robaseifeddine** [comment]
on a étudié la tracabilite interne des items (entre les salles et la store... on spécifiant  :
- sauvegarder : l'entre et la sortie des Item en store, la tracabilite les items entre les salle, définir les types de salle (chaque type ayant son item spécifique for exemple salle de cours, salle des cuisine ,  la direction ,...).
note:
en utilisant le parcode  pour le modifier les data (dans la porte).

**Comment by majedlb** [comment]
Nous sommes dans le cas d'une entreprise présentant plusieurs branches qui sont à leurs tours   organisées en différents départements et sous-départements.

Chacune de ces branches peut spécifier ses besoins en matériels et fournitures ainsi qu'évaluer et choisir les différents marques et fournisseurs d'une façon indépendante. Chaque branche possède sa propre "gestion des stock" et ce service est responsable de la gestion adéquate des approvisionnements et de leur rotation efficace intra-branche ainsi que des transferts entre-branches en cas de besoin. L'objectif de ce projet est d'organiser cette gestion des stocks.
Nous proposons une organisation selon les étapes suivantes:
•	L'entreprise est organisée en différentes branches
•	Chaque Branche a une seule location et est divisée en différents départements.
•	Chaque département présente différents sous-départements ou sections, chacun présentant plusieurs employés.
•	A chaque employé est attribué un seul poste principal.
•	Chaque branche possède un seul Stock de matériels, et ces différents produits sont organisés en catégories.
•	Ce stock fournit les différents départements de la même branche.
•	Ce stock peut fournir aussi les stocks des autres branches. Ce transfert est effectué par le service de transport (service postal de l'entreprise).

•	A chaque acquisition d'un nouveau produit, un code lui sera attribué  selon sa catégorie.
Ainsi, pour chaque produit, et à n'importe quel moment et grâce à son code, un repérage et distribution rapide intra-branche ou entre-branches sera possible, de même qu'un inventaire minutieux et continuel.

**Comment by majedlb** [comment]
Nous sommes dans le cas d'une entreprise présentant plusieurs branches qui sont à leurs tours organisées en différents départements et sous-départements.

Chacune de ces branches peut spécifier ses besoins en matériels et fournitures ainsi qu'évaluer et choisir les différents marques et fournisseurs d'une façon indépendante. Chaque branche possède sa propre "gestion des stock" et ce service est responsable de la gestion adéquate des approvisionnements et de leur rotation efficace intra-branche ainsi que des transferts entre-branches en cas de besoin. L'objectif de ce projet est d'organiser cette gestion des stocks.

Nous proposons une organisation selon les étapes suivantes:

•	L'entreprise est organisée en différentes branches
•	Chaque Branche a une seule location et est divisée en différents départements.
•	Chaque département présente différents sous-départements ou sections, chacun présentant    
        plusieurs employés.
•	A chaque employé est attribué un seul poste principal.
•	Chaque branche possède un seul Stock de matériels, et ces différents produits sont organisés 
         en catégories.
•	Ce stock fournit les différents départements de la même branche.
•	Ce stock peut fournir aussi les stocks des autres branches. Ce transfert est effectué par le 
        service de transport (service postal de l'entreprise).
•	A chaque acquisition d'un nouveau produit, un code lui sera attribué  selon sa catégorie.

Ainsi, pour chaque produit, et à n'importe quel moment et grâce à son code, un repérage et distribution rapide intra-branche ou entre-branches sera possible, de même qu'un inventaire minutieux et continuel.

**Comment by majedlb** [comment]
![shema](https://cloud.githubusercontent.com/assets/12184591/8474476/068b7f10-20b9-11e5-981e-155d150a6f7c.jpg)

**Comment by majedlb** [comment]
![mld](https://cloud.githubusercontent.com/assets/12184591/8474484/18537590-20b9-11e5-8463-52dde79d2e4a.jpg)
