### ISSUE TITLE
partie gestion intérieure du stock 

### ISSUE THREAD

**Issue by michel-el-hajj** [ISSAE/smb215-16#20]
- créer la base de donnée
- créer la page "login" pour que seulement les responsables auront l'authentification pour modifier le stock
- créer la page qui permet à l'employé de modifier le stock
- créer un lien entre les différents centre pour faire la modification pour les produits utilisés par plusieurs centres
- créer la page qui permet l'employé de voir la quantité restante dans le stock
- créer la page des produits restants en attente comme le projecteur

**Comment by nachkar** [comment]
![sequence-diagram-for-facebook-data-access](https://cloud.githubusercontent.com/assets/9281702/9365589/043975b4-46bb-11e5-9cd5-6ef2c0f263b7.jpg)
Gestion Stock Intérieur : https://github.com/nachkar/SMB215 
Added Facebook login

**Comment by michel-el-hajj** [comment]
N.B.: la partie est en train d'être développé par moi et Noel Achkar

**Comment by nachkar** [comment]
Mr Pascal @pascalfares en plus du website que nous continuons a développer ,nous avons créer une application iOS pour controller le stock intérieur (ScreenShots : https://github.com/nachkar/SMB215-iOS-App/tree/master/ScreenShots) vous pouvez trouver le code dans ce répositoire : https://github.com/nachkar/SMB215-iOS-App/

Nous travaillons en plus du website et en meme temps sur une application androïde de fonctionnalité similaire à celle ci.

**Comment by pascalfares** [comment]
Comment je fais pour faire des test?

**Comment by pascalfares** [comment]
le cours SMB215 c'est du JAVA!

**Comment by smb21515** [comment]
Bonjour Mr. Pascal,

Concernant le SMB215, vous avez dit qu'on peut utiliser la technologie
android, ......
Alors, on a fait une application pour IOS, maintenant nous travaillons sur
une application android et nous allons finir avec un website.
Nous avons pris la décision d'être différent des autres en créant des
applications.
Si l'application android est inutile pour le SMB215, s'il vous plait
dites-nous pour travailler seulement sur le website.

Merci d'avance.

2015-11-11 0:27 GMT+02:00 Pascal Fares <notifications@github.com>:

**Comment by michel-el-hajj** [comment]
N.B.: c'est moi qui a fait le dernier "comment".
