### ISSUE TITLE
Rejoindre le groupe et ce projet

### ISSUE THREAD

**Issue by pascalfares** [ISSAE/smb215-16#22]
A tous les auditeurs SMB215 2016

rejoindre le groupe : https://groups.google.com/a/cnamliban.org/forum/#!forum/smb215-2016

Quand c'est terminé faire reply ici....

**Comment by chakti-farid** [comment]
Done.

**Comment by Peter-eid** [comment]
Done.

Peter Eid

**Comment by nachkar** [comment]
Done. Waiting your approval.

**Comment by pascalfares** [comment]
Verifier que vous ête membre de l'équipe https://github.com/orgs/ISSAE/teams/smb215

En principe vous ressevez une invitation par email...

**Comment by adeiry** [comment]
Done.

**Comment by antonio-serhaly** [comment]
done


________________________________

**Comment by malakKays** [comment]
done :)

**Comment by esfeir** [comment]
Done
