### ISSUE TITLE
1.2 Réalisé en Tomcat un module SSO basée OAUTH fonctionnant avec google minimum et enventellement facebook, twitter, openid, ...

### ISSUE THREAD

**Issue by pascalfares** [ISSAE/smb215-16#8]
Spécifier concevoir et réaliser un module SSO utilisable dans tomcat, fonctionnant au moins avec google

**Comment by Ibrahim-Keyrouz** [comment]
Bonjour Dr @pascalfares , 

 Pouvez vous me dire quel article correspond a ce qu'on veut  : 
1- premier article sur OAuth 1.0
2- dexieme sur OAuth 2.0 
3- troisieme sur JOAuth 

Merci.

**Comment by Guitta** [comment]
Quelques sites utiles OAuth :
http://oauth.net/
http://2rdscreenretargeting.blogspot.com/2012/06/secure-jersey-with-oauth2.html
http://tutorials.jenkov.com/oauth2/authorization.html
 http://stackoverflow.com/questions/5297730/java-tomcat-how-to-use-joauth-properly
 http://www.ibm.com/developerworks/library/se-oauthjavapt3/index.html

**Comment by Ibrahim-Keyrouz** [comment]
@Guitta  I've found those links and I'm thankful for ur help , but I need to know are we talking about OAuth or JOAuth

**Comment by Ibrahim-Keyrouz** [comment]
![webflow](https://cloud.githubusercontent.com/assets/4200166/7686872/a32669ba-fda1-11e4-8fc6-44634f749445.png)

**Comment by Guitta** [comment]
Mais en fait : JOauth is a Java library for authenticating HTTP Requests using OAuth.

**Comment by smb21515** [comment]
Tomcat sera le client oauth (pas necessairement le serveur)

Il faut bien sure comprendre le protocole Oauth (2 ... 1 est inutile)

Je ne sais rien de Joauth

**Comment by Ibrahim-Keyrouz** [comment]
@smb21515  merci
