### ISSUE TITLE
2.1- Definir le modèle statique (diagrammes de classes)

### ISSUE THREAD

**Issue by pascalfares** [ISSAE/smb215-16#9]
Definir le modèle statique (diagrammes de classes)

**Comment by ShawkiShehadeh** [comment]
![classdiagram1](https://cloud.githubusercontent.com/assets/12253555/7671019/80035d7c-fcc4-11e4-91de-19d2a6fd5d05.jpg)

**Comment by ShawkiShehadeh** [comment]
![classdiagram2](https://cloud.githubusercontent.com/assets/12253555/7671021/8f8a21a4-fcc4-11e4-9028-a673416c7361.jpg)
